const MAP_URL='https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_1_states_provinces.geojson';
const C={DE:['Германия','🇩🇪','#647b4a'],PL:['Польша','🇵🇱','#b56b67'],FR:['Франция','🇫🇷','#5476a8'],IT:['Италия','🇮🇹','#6b8b68'],GB:['Великобритания','🇬🇧','#6a667e'],RU:['Россия','🇷🇺','#7b5d57'],UA:['Украина','🇺🇦','#9a8150'],BY:['Беларусь','🇧🇾','#7b8760'],CZ:['Чехия','🇨🇿','#7c7795'],SK:['Словакия','🇸🇰','#89705a'],AT:['Австрия','🇦🇹','#8a6c69'],HU:['Венгрия','🇭🇺','#8c7b52'],RO:['Румыния','🇷🇴','#6d8875'],BG:['Болгария','🇧🇬','#7e6f8f'],GR:['Греция','🇬🇷','#617b8e'],TR:['Турция','🇹🇷','#8a6c55'],ES:['Испания','🇪🇸','#8d7651'],PT:['Португалия','🇵🇹','#6d8070'],NL:['Нидерланды','🇳🇱','#8b7055'],BE:['Бельгия','🇧🇪','#6e7088'],CH:['Швейцария','🇨🇭','#7b7b7b'],DK:['Дания','🇩🇰','#8b6460'],NO:['Норвегия','🇳🇴','#667d87'],SE:['Швеция','🇸🇪','#607d71'],FI:['Финляндия','🇫🇮','#6c7685'],EE:['Эстония','🇪🇪','#6f7d6b'],LV:['Латвия','🇱🇻','#856c66'],LT:['Литва','🇱🇹','#6f8161'],MD:['Молдова','🇲🇩','#81795a'],RS:['Сербия','🇷🇸','#8a6565'],HR:['Хорватия','🇭🇷','#6d7f67'],SI:['Словения','🇸🇮','#71818c'],BA:['Босния и Герцеговина','🇧🇦','#7e7464'],ME:['Черногория','🇲🇪','#736b7c'],AL:['Албания','🇦🇱','#78656f'],MK:['Северная Македония','🇲🇰','#8b7555'],IE:['Ирландия','🇮🇪','#5f8065'],IS:['Исландия','🇮🇸','#607a89'],XK:['Косово','🇽🇰','#80706e']};
const EUROPE=Object.keys(C);
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const svg=$('world'), state={player:'DE',speed:1,paused:false,date:new Date('1939-09-01T00:00:00Z'),features:[],prov:[],units:[],selectedProv:null,selectedUnit:null,wars:new Set(['DE|PL','DE|FR']),fronts:[],resources:{manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100},tech:{infantry:false,armor:false,industry:false,logistics:false,air:false}};
let W=0,H=0,view={minLon:-15,maxLon:55,minLat:32,maxLat:72},zoom=1,panX=0,panY=0,timer=null;
const safe=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const pair=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
const atWar=(a,b)=>a&&b&&a!==b&&state.wars.has(pair(a,b));
const nameIso=iso=>C[iso]?.[0]||iso||'Неизвестно';
function log(t){const e=document.createElement('div');e.textContent=t;$('#log').prepend(e);setTimeout(()=>e.remove(),6500)}
function propName(f){return f.properties?.name_ru||f.properties?.name_en||f.properties?.name||'Провинция'}
function propIso(f){return f.properties?.iso_a2||''}
function coordsOf(g){const out=[];const walk=a=>Array.isArray(a)&&typeof a[0]==='number'?out.push(a):Array.isArray(a)&&a.forEach(walk);walk(g.coordinates);return out}
function centerFeature(f){if(Number.isFinite(f.properties?.longitude)&&Number.isFinite(f.properties?.latitude))return [f.properties.longitude,f.properties.latitude];const a=coordsOf(f.geometry);if(!a.length)return [20,50];let x=0,y=0;a.forEach(p=>{x+=p[0];y+=p[1]});return [x/a.length,y/a.length]}
function project(lon,lat){const x=((lon-view.minLon)/(view.maxLon-view.minLon))*W*zoom+panX;const y=((view.maxLat-lat)/(view.maxLat-view.minLat))*H*zoom+panY;return [x,y]}
function geometryPath(g){if(!g)return '';const poly=r=>r.map((p,i)=>{const [x,y]=project(p[0],p[1]);return `${i?'L':'M'}${Number(x.toFixed(2))},${Number(y.toFixed(2))}`}).join('')+'Z';if(g.type==='Polygon')return g.coordinates.map(poly).join(' ');if(g.type==='MultiPolygon')return g.coordinates.map(p=>p.map(poly).join(' ')).join(' ');return ''}
function featureSvg(f,i){const d=document.createElementNS('http://www.w3.org/2000/svg','path');d.classList.add('province');d.dataset.id=i;d.setAttribute('d',geometryPath(f));d.addEventListener('click',()=>selectProv(i));d.addEventListener('contextmenu',e=>{e.preventDefault();issueOrder(i)});d.addEventListener('mousemove',e=>tooltip(e,i));d.addEventListener('mouseleave',hideTip);return d}
function fallbackFeatures(){const boxes={IS:[-24,-14,63,67],IE:[-10,-6,51,55],GB:[-8,2,50,59],PT:[-9.5,-6.2,37,42],ES:[-9.5,3.3,36,44],FR:[-5,8,42,51],BE:[2.5,6.4,49.4,51.6],NL:[3.2,7.3,50.7,53.6],DE:[5.8,15.2,47.2,55.1],DK:[8,12.7,54.5,57.8],NO:[4,31,58,71],SE:[11,24.5,55,69],FI:[20,32,59.5,70],EE:[21.5,28.2,57.4,59.8],LV:[20.7,28.3,55.6,58.1],LT:[21,26.8,53.8,56.5],PL:[14,24.2,49,54.9],CZ:[12,19,48.5,51.2],SK:[16.8,22.6,47.7,49.7],AT:[9.5,17.2,46.3,49.1],CH:[5.9,10.5,45.8,47.9],IT:[7,18.7,36.5,47],ME:[18.4,20.4,41.8,43.6],ES:[-9.5,3.3,36,44],RO:[20,29.7,43.6,48.3],HU:[16,23,45.7,48.6],RS:[18.8,23,42.2,46.3],HR:[13.4,19.5,42.3,46.6],SI:[13.3,16.7,45.4,46.9],BA:[15.7,19.7,42.5,45.4],AL:[19,21.1,39.6,42.7],MK:[20.4,23,40.7,42.4],GR:[19.4,28.3,34.8,41.8],BG:[22.3,28.7,41.1,44.3],UA:[22,40.2,44.3,52.4],BY:[23,32.8,51.2,56.2],MD:[26.5,30.2,45.4,48.6],RU:[27,55,41.5,71],TR:[26,45,35.7,42.2]};return Object.entries(boxes).filter(([iso])=>C[iso]).map(([iso,b])=>{const [a,bx,c,d]=b;return {type:'Feature',properties:{iso_a2:iso,name_ru:C[iso][0]},geometry:{type:'Polygon',coordinates:[[[a,c],[bx,c],[bx,d],[a,d],[a,c]]]}}})}
async function fetchWithTimeout(url,ms){const ctrl=new AbortController(),t=setTimeout(()=>ctrl.abort(),ms);try{const r=await fetch(url,{signal:ctrl.signal,cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(t)}}
async function loadMap(){updateMapStatus('Загрузка геоданных…');try{const j=await fetchWithTimeout(MAP_URL,7000),fs=(j.features||[]).filter(f=>EUROPE.includes(propIso(f)));if(!fs.length)throw new Error('Нет европейских провинций');state.features=fs;updateMapStatus(`Реальная карта загружена: ${fs.length} провинций`)}catch(e){state.features=fallbackFeatures();updateMapStatus('Внешняя карта недоступна — включена офлайн-карта. Игра продолжает работать.');log('Natural Earth не ответил за 7 секунд; включён офлайн-режим без ошибки интернета.')}buildProvinces();drawMap();startScenario()}
function buildProvinces(){state.prov=state.features.map((f,i)=>{const c=centerFeature(f);return {id:i,feature:f,owner:propIso(f),original:propIso(f),name:propName(f),cx:c[0],cy:c[1],units:[]}})}
function boundsOf(f){const a=[];const walk=g=>Array.isArray(g)&&typeof g[0]==='number'?a.push(g):Array.isArray(g)&&g.forEach(walk);walk(f.feature.geometry.coordinates);if(!a.length)return [0,0,0,0];let minX=999,maxX=-999,minY=999,maxY=-999;a.forEach(p=>{minX=Math.min(minX,p[0]);maxX=Math.max(maxX,p[0]);minY=Math.min(minY,p[1]);maxY=Math.max(maxY,p[1])});return [minX,minY,maxX,maxY]}
function adjacent(a,b){const A=boundsOf(a),B=boundsOf(b),gx=Math.max(0,A[0]-B[2],B[0]-A[2]),gy=Math.max(0,A[1]-B[3],B[1]-A[3]);return Math.hypot(gx,gy)<1.15}
function rebuildFronts(){state.fronts=[];for(let i=0;i<state.prov.length;i++)for(let j=i+1;j<state.prov.length;j++){const a=state.prov[i],b=state.prov[j];if(a.owner!==b.owner&&atWar(a.owner,b.owner)&&adjacent(a,b))state.fronts.push([a,b])}}
function drawMap(){svg.replaceChildren();W=$('map').clientWidth;H=$('map').clientHeight;const sea=document.createElementNS('http://www.w3.org/2000/svg','rect');sea.setAttribute('width','100%');sea.setAttribute('height','100%');sea.setAttribute('fill','#3f5a68');svg.appendChild(sea);state.prov.forEach((p,i)=>svg.appendChild(featureSvg(p.feature,i)));renderOverlay()}
function color(iso){return C[iso]?.[2]||'#5e686e'}
function renderOverlay(){state.prov.forEach(p=>{const el=svg.querySelector(`path.province[data-id="${p.id}"]`);if(el){el.setAttribute('fill',color(p.owner));el.classList.toggle('selected',p.id===state.selectedProv)}});svg.querySelectorAll('.overlay').forEach(e=>e.remove());const g=document.createElementNS('http://www.w3.org/2000/svg','g');g.classList.add('overlay');state.fronts.forEach((f,i)=>{const l=document.createElementNS('http://www.w3.org/2000/svg','path');l.classList.add('front',i%2?'secondary':'');const [x1,y1]=project(f[0].cx,f[0].cy),[x2,y2]=project(f[1].cx,f[1].cy);l.setAttribute('d',`M${x1},${y1}L${x2},${y2}`);g.appendChild(l)});state.units.forEach(u=>{const p=state.prov[u.prov];if(!p)return;const [x,y]=project(p.cx,p.cy);const t=document.createElementNS('http://www.w3.org/2000/svg','text');t.classList.add('unit-marker');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('fill',u.owner===state.player?'#fff3a5':'#ffb0a5');t.textContent=`⚔${p.units.length}`;g.appendChild(t)});svg.appendChild(g)}
function tooltip(e,id){const p=state.prov[id],tip=$('tooltip');tip.style.display='block';tip.innerHTML=`<b>${safe(p.name)}</b><br>${safe(nameIso(p.owner))}<br>Дивизий: ${p.units.length}${p.owner!==state.player&&atWar(state.player,p.owner)?'<br><span class="warn">⚔ Участок фронта</span>':''}`;const r=$('map').getBoundingClientRect();tip.style.left=(e.clientX-r.left+14)+'px';tip.style.top=(e.clientY-r.top+14)+'px'}
function hideTip(){$('tooltip').style.display='none'}
function selectProv(id){state.selectedProv=id;const p=state.prov[id];const own=p.units.find(u=>u.owner===state.player);state.selectedUnit=own?own.id:null;render()}
function addUnit(owner,type,prov){const u={id:state.units.length,owner,type,prov,target:null,remaining:0,org:100,strength:type==='tank'?125:type==='art'?105:100};state.units.push(u);state.prov[prov].units.push(u);return u}
function findProv(iso,needName=''){const ps=state.prov.filter(p=>p.owner===iso);if(needName){const f=ps.find(p=>p.name.toLowerCase().includes(needName.toLowerCase()));if(f)return f}return ps[Math.floor(ps.length/2)]||null}
function startScenario(){state.date=new Date('1939-09-01T00:00:00Z');state.units=[];state.selectedProv=null;state.selectedUnit=null;state.resources={manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100};state.tech={infantry:false,armor:false,industry:false,logistics:false,air:false};state.prov.forEach(p=>{p.owner=p.original;p.units=[]});const setup={DE:['Berlin','Bavaria','Sachsen','Brandenburg'],PL:['Mazovia','Silesia','Lodz'],FR:['Île-de-France','Nord','Lorraine'],IT:['Lombardy','Lazio','Veneto'],GB:['England'],RU:['Moscow','Smolensk','Leningrad'],UA:['Kyiv'],RO:['Bucharest']};Object.entries(setup).forEach(([iso,names])=>names.forEach(n=>{const p=findProv(iso,n);if(p)addUnit(iso,'inf',p.id)}));['DE','PL','FR','IT','RU','UA'].forEach(iso=>{const ps=state.prov.filter(p=>p.owner===iso);for(let i=0;i<Math.min(4,ps.length);i++){const p=ps[i*2];if(p&&!p.units.length)addUnit(iso,'inf',p.id)}});rebuildFronts();state.paused=false;render();log('Кампания началась: 1 сентября 1939. Это игровая альтернативная история.')}
function issueOrder(targetId){if(state.selectedUnit==null){log('Сначала выбери свою дивизию.');return}const u=state.units[state.selectedUnit];if(!u||u.owner!==state.player)return;const a=state.prov[u.prov],b=state.prov[targetId];if(a.id===b.id)return;if(!adjacent(a,b)){log('Приказ можно отдавать соседней провинции. Для дальнего марша двигайся поэтапно.');return}if(b.owner!==u.owner&&!atWar(u.owner,b.owner)){log('Сначала объяви войну этой стране.');return}u.target=b.id;u.remaining=5;log(`${typeName(u.type)} → ${b.name}`);render()}
function typeName(t){return t==='tank'?'Танковая дивизия':t==='art'?'Артиллерийская группа':'Пехотная дивизия'}
function removeUnit(id){const u=state.units.find(x=>x.id===id);if(!u)return;state.prov[u.prov].units=state.prov[u.prov].units.filter(x=>x.id!==id);state.units=state.units.filter(x=>x.id!==id);state.units.forEach((x,i)=>x.id=i);state.selectedUnit=null}
function moveUnit(u,to){state.prov[u.prov].units=state.prov[u.prov].units.filter(x=>x.id!==u.id);u.prov=to;state.prov[to].units.push(u);u.target=null;u.remaining=0;u.org=Math.min(100,u.org+8);state.prov[to].owner=u.owner;rebuildFronts()}
function fight(target,u){const defenders=target.units.filter(x=>x.owner!==u.owner),atk=u.strength*(state.tech.infantry&&u.type==='inf'?1.2:1),def=defenders.reduce((s,x)=>s+x.strength,0);if(!defenders.length){moveUnit(u,target.id);return}if(atk>def*0.9){defenders.slice().forEach(d=>{d.org-=Math.max(7,atk/Math.max(1,def));if(d.org<=0)removeUnit(d.id)});u.org-=4;moveUnit(u,target.id);log(`${typeName(u.type)} прорвала оборону в ${target.name}.`)}else{u.org-=6;defenders.forEach(d=>d.org-=2);if(u.org<25){u.target=null;log(`${typeName(u.type)} потеряла организацию и отступает.`)}}}
function tick(){if(state.paused)return;state.date=new Date(state.date.getTime()+state.speed*60*60*1000);state.resources.pp+=state.resources.factories*0.08*state.speed;state.resources.oil=Math.max(0,state.resources.oil-0.3*state.speed);state.resources.steel+=state.resources.factories*0.04*state.speed;state.units.slice().forEach(u=>{if(u.org<100)u.org=Math.min(100,u.org+0.8*state.speed);if(u.target!=null){u.remaining-=state.speed;if(u.remaining<=0){const b=state.prov[u.target];b.owner===u.owner?moveUnit(u,b.id):fight(b,u)}}});rebuildFronts();render()}
function render(){renderStats();renderArmy();renderProd();renderTech();renderCountries();renderOverlay()}
function renderStats(){const c=C[state.player]||['—','★'];$('countryName').textContent=c[0];$('countrySub').textContent=`${state.player} · ${state.prov.filter(p=>p.owner===state.player).length} провинций`;$('flag').textContent=c[1];['manpower','factories','equipment','oil','steel','pp'].forEach(k=>$(k).textContent=Math.floor(state.resources[k]));$('date').textContent=state.date.toLocaleString('ru-RU',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'});$('speed').textContent='▶ '+state.speed+'x';$('pause').textContent=state.paused?'▶ Продолжить':'⏸ Пауза'}
function renderArmy(){const p=state.selectedProv!=null?state.prov[state.selectedProv]:null;$('selection').innerHTML=p?`Выбрано: <b>${safe(p.name)}</b> · ${safe(nameIso(p.owner))}`:'';const us=state.units.filter(u=>u.owner===state.player);$('units').innerHTML=us.map(u=>{const p=state.prov[u.prov];return `<div class="unit ${u.id===state.selectedUnit?'sel':''}" data-u="${u.id}"><div class="top"><b>${typeName(u.type)}</b><span>${safe(p.name)}</span></div><div>Организация ${Math.round(u.org)} · Сила ${Math.round(u.strength)}</div><div class="meter"><i style="width:${u.org}%"></i></div>${u.target!=null?`<small>Приказ: ${safe(state.prov[u.target].name)} · ${Math.ceil(u.remaining)}ч</small>`:''}</div>`}).join('')||'<div class="notice">Дивизий нет.</div>';$$('.unit[data-u]').forEach(el=>el.onclick=()=>{state.selectedUnit=+el.dataset.u;state.selectedProv=state.units[state.selectedUnit].prov;render()})}
function renderProd(){$('queue').innerHTML=`<div class="queue-row">Боеприпасы: +${Math.floor(state.resources.factories*0.7)} ед./час</div><div class="queue-row">Техника: +${Math.floor(state.resources.factories*0.35)} ед./час</div>`}
function renderTech(){const techs=[['infantry','Пехотное оружие','+20% атака пехоты',40],['armor','Броня','усиление танков',55],['industry','Промышленность','+4 фабрики',45],['logistics','Логистика','меньше потери организации',50],['air','Авиация','поддержка атаки',60]];$('techs').innerHTML=techs.map(([id,n,d,c])=>`<div class="tech"><div><b>${n}</b><small>${d} · ${c}🏛️</small></div><button data-tech="${id}" ${state.tech[id]||state.resources.pp<c?'disabled':''}>${state.tech[id]?'Изучено':'Изучить'}</button></div>`).join('');$$('[data-tech]').forEach(b=>b.onclick=()=>{const id=b.dataset.tech,c={infantry:40,armor:55,industry:45,logistics:50,air:60}[id];if(state.tech[id]||state.resources.pp<c)return;state.resources.pp-=c;state.tech[id]=true;if(id==='industry')state.resources.factories+=4;log(`Исследовано: ${b.parentElement.querySelector('b').textContent}`);render()})}
function renderCountries(){const ids=EUROPE.filter(i=>state.prov.some(p=>p.owner===i));$('countries').innerHTML=ids.map(i=>{const n=state.prov.filter(p=>p.owner===i).length,war=atWar(state.player,i);return `<div class="country-row"><div><b>${C[i][1]} ${C[i][0]}</b><div class="small">${n} пров. · ${war?'война':'мир'}</div></div>${i===state.player?'':`<button data-war="${i}" ${war?'disabled':''}>${war?'Война':'Объявить войну'}</button>`}</div>`}).join('');$$('[data-war]').forEach(b=>b.onclick=()=>{const iso=b.dataset.war;state.wars.add(pair(state.player,iso));rebuildFronts();log(`Объявлена война: ${nameIso(iso)}.`);render()})}
function updateMapStatus(t){$('mapStatus').textContent=t}
function saveGame(){localStorage.setItem('iron-front-save',JSON.stringify({player:state.player,speed:state.speed,paused:state.paused,date:state.date.toISOString(),wars:[...state.wars],prov:state.prov.map(p=>({owner:p.owner})),units:state.units.map(u=>({...u})),resources:state.resources,tech:state.tech}));log('Игра сохранена локально.')}
function loadGame(){try{const s=JSON.parse(localStorage.getItem('iron-front-save')||'null');if(!s){log('Сохранения нет.');return}state.player=s.player;state.speed=s.speed;state.paused=s.paused;state.date=new Date(s.date);state.wars=new Set(s.wars);state.resources=s.resources;state.tech=s.tech;state.prov.forEach((p,i)=>{p.owner=s.prov[i]?.owner||p.original;p.units=[]});state.units=s.units.map(u=>({...u}));state.units.forEach(u=>state.prov[u.prov]?.units.push(u));rebuildFronts();$('country').value=state.player;render();log('Сохранение загружено.')}catch(e){log('Сохранение повреждено. Начни новую игру.')}}
function fillCountrySelect(){const sel=$('country');sel.innerHTML=EUROPE.map(i=>`<option value="${i}">${C[i][1]} ${C[i][0]}</option>`).join('');sel.value=state.player;sel.onchange=()=>{state.player=sel.value;startScenario()}}
function wire(){fillCountrySelect();$$('.speeds button').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;render()});$('pause').onclick=()=>{state.paused=!state.paused;render()};$('newGame').onclick=startScenario;$('save').onclick=saveGame;$('load').onclick=loadGame;$('buildFactory').onclick=()=>{if(state.resources.pp<50){log('Не хватает политической власти.');return}state.resources.pp-=50;state.resources.factories++;render()};[['recruitInf','inf',30],['recruitArt','art',45],['recruitTank','tank',70]].forEach(([id,type,cost])=>$(id).onclick=()=>{if(state.resources.manpower<20||state.resources.equipment<cost){log('Не хватает людских ресурсов или техники.');return}const p=state.prov.find(p=>p.owner===state.player);if(!p){log('Нет контролируемой провинции.');return}state.resources.manpower-=20;state.resources.equipment-=cost;addUnit(state.player,type,p.id);render()});$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tabbody').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});window.addEventListener('resize',drawMap);window.addEventListener('keydown',e=>{if(e.code==='Space'){state.paused=!state.paused;render()}if(['1','2','3'].includes(e.key)){state.speed=+e.key;render()}});let dragging=false,last=[0,0];svg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(1,Math.min(4,zoom*(e.deltaY<0?1.15:0.87)));drawMap();render()},{passive:false});svg.addEventListener('mousedown',e=>{if(e.button===0){dragging=true;last=[e.clientX,e.clientY]}});window.addEventListener('mouseup',()=>dragging=false);window.addEventListener('mousemove',e=>{if(dragging){panX+=e.clientX-last[0];panY+=e.clientY-last[1];last=[e.clientX,e.clientY];drawMap();render()}})}
wire();timer=setInterval(tick,1000);loadMap();