const DATA_URLS=[
 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_1_states_provinces.geojson',
 'https://cdn.jsdelivr.net/gh/nvkelso/natural-earth-vector@master/geojson/ne_110m_admin_1_states_provinces.geojson'
];
const C={DE:['Германия','🇩🇪','#647b4a'],PL:['Польша','🇵🇱','#b56b67'],FR:['Франция','🇫🇷','#5476a8'],IT:['Италия','🇮🇹','#6b8b68'],GB:['Великобритания','🇬🇧','#6a667e'],RU:['Россия','🇷🇺','#7b5d57'],UA:['Украина','🇺🇦','#9a8150'],BY:['Беларусь','🇧🇾','#7b8760'],CZ:['Чехия','🇨🇿','#7c7795'],SK:['Словакия','🇸🇰','#89705a'],AT:['Австрия','🇦🇹','#8a6c69'],HU:['Венгрия','🇭🇺','#8c7b52'],RO:['Румыния','🇷🇴','#6d8875'],BG:['Болгария','🇧🇬','#7e6f8f'],GR:['Греция','🇬🇷','#617b8e'],TR:['Турция','🇹🇷','#8a6c55'],ES:['Испания','🇪🇸','#8d7651'],PT:['Португалия','🇵🇹','#6d8070'],NL:['Нидерланды','🇳🇱','#8b7055'],BE:['Бельгия','🇧🇪','#6e7088'],CH:['Швейцария','🇨🇭','#7b7b7b'],DK:['Дания','🇩🇰','#8b6460'],NO:['Норвегия','🇳🇴','#667d87'],SE:['Швеция','🇸🇪','#607d71'],FI:['Финляндия','🇫🇮','#6c7685'],EE:['Эстония','🇪🇪','#6f7d6b'],LV:['Латвия','🇱🇻','#856c66'],LT:['Литва','🇱🇹','#6f8161'],MD:['Молдова','🇲🇩','#81795a'],RS:['Сербия','🇷🇸','#8a6565'],HR:['Хорватия','🇭🇷','#6d7f67'],SI:['Словения','🇸🇮','#71818c'],BA:['Босния','🇧🇦','#7e7464'],AL:['Албания','🇦🇱','#78656f'],MK:['Северная Македония','🇲🇰','#8b7555'],IE:['Ирландия','🇮🇪','#5f8065'],IS:['Исландия','🇮🇸','#607a89'],XK:['Косово','🇽🇰','#80706e']};
const KEYS=Object.keys(C);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const game={player:'DE',speed:1,paused:false,date:new Date('1939-09-01T00:00:00Z'),features:[],prov:[],units:[],selectedProv:null,selectedUnit:null,wars:new Set(['DE|PL','DE|FR']),fronts:[],queue:[],resources:{manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100,research:40},tech:{infantry:false,armor:false,industry:false,logistics:false,air:false},capital:{DE:null,PL:null,FR:null,RU:null,IT:null},originalOwners:[]};
let svg,gMap,gFront,gOrder,gUnit,gLabel,projection,path,width,height,tipTimer;
const colorFor=iso=>C[iso]?.[2]||'#5e686e';
const nameForIso=iso=>C[iso]?.[0]||iso||'Нейтральная территория';
const pn=f=>f.properties.name_ru||f.properties.name_en||f.properties.name||'Без имени';
const pCountry=f=>f.properties.iso_a2||'';
function pair(a,b){return a<b?`${a}|${b}`:`${b}|${a}`}
function atWar(a,b){return a&&b&&a!==b&&game.wars.has(pair(a,b))}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function dist(a,b){const dx=(a.cx-b.cx)*Math.cos((a.cy+b.cy)*Math.PI/360),dy=a.cy-b.cy;return Math.hypot(dx,dy)}
function log(msg){const e=document.createElement('div');e.textContent=msg;$('#log').prepend(e);setTimeout(()=>e.remove(),6500)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function loadJson(){for(const u of DATA_URLS){try{const r=await fetch(u,{cache:'force-cache'});if(r.ok)return await r.json()}catch(e){}}throw new Error('Не удалось загрузить GeoJSON')}
function baseProvince(f,i){const c=d3.geoCentroid(f);return {id:i,feature:f,owner:pCountry(f),original:pCountry(f),name:pn(f),cx:c[0],cy:c[1],units:[],label:i}};
function setupMap(){svg=d3.select('#world');width=$('#map').clientWidth;height=$('#map').clientHeight;svg.attr('viewBox',`0 0 ${width} ${height}`);projection=d3.geoMercator();projection.fitExtent([[18,18],[width-18,height-18]],{type:'FeatureCollection',features:game.features});path=d3.geoPath(projection);svg.selectAll('*').remove();gMap=svg.append('g').attr('class','maproot');gFront=gMap.append('g');gOrder=gMap.append('g');gMap.append('g').attr('class','sea-grid');gUnit=gMap.append('g');gLabel=gMap.append('g');svg.call(d3.zoom().scaleExtent([1,9]).on('zoom',e=>gMap.attr('transform',e.transform)));drawProvinces()}
function drawProvinces(){const sel=gMap.selectAll('path.province').data(game.prov,d=>d.id);sel.enter().append('path').attr('class','province').merge(sel).attr('d',d=>path(d.feature)).on('click',(_,d)=>selectProvince(d.id)).on('contextmenu',(e,d)=>{e.preventDefault();issueOrder(d.id,e)}).on('mousemove',(e,d)=>showTip(e,d)).on('mouseleave',hideTip);sel.exit().remove();gLabel.selectAll('*').remove()}
function showTip(e,p){const enemy=game.prov.filter(x=>x.id!==p.id&&x.owner!==p.owner&&atWar(p.owner,x.owner)&&dist(p,x)<5.2).length;$('#tooltip').style.display='block';$('#tooltip').innerHTML=`<b>${esc(p.name)}</b><br>${esc(nameForIso(p.owner))}<br>Дивизий: ${p.units.length}${enemy?`<br><span class="warn">⚔ На фронте</span>`:''}`;const r=$('#map').getBoundingClientRect();$('#tooltip').style.left=(e.clientX-r.left+14)+'px';$('#tooltip').style.top=(e.clientY-r.top+14)+'px'}
function hideTip(){$('#tooltip').style.display='none'}
function selectProvince(id){game.selectedProv=id;const p=game.prov[id];const ownUnit=p.units.find(u=>u.owner===game.player);game.selectedUnit=ownUnit?ownUnit.id:null;render();}
function issueOrder(targetId,e){if(game.selectedUnit==null){log('Сначала выбери свою дивизию.');return}const u=game.units.find(x=>x.id===game.selectedUnit);if(!u||u.owner!==game.player)return;const a=game.prov[u.prov],b=game.prov[targetId];if(!b||a.id===b.id)return;const d=dist(a,b);if(d>6.5){log('Слишком далеко. Дивизия может приказ получить только на соседний участок фронта.');return}if(b.owner!==u.owner&&!atWar(u.owner,b.owner)){log('Сначала объяви войну этой стране.');return}u.target=targetId;u.remaining=clamp(4+d*5,5,36);log(`${u.name}: приказ → ${b.name}`);render()}
function addUnit(owner,type,provId=null){const p=provId!=null?game.prov[provId]:findCapital(owner);if(!p)return null;const mult={inf:1,art:1.12,tank:1.55}[type]||1;const u={id:game.units.length,owner,type,prov:p.id,target:null,remaining:0,org:100,strength:type==='tank'?125:type==='art'?105:100,attack:(30+game.resources.factories)*mult};game.units.push(u);p.units.push(u);return u}
function findCapital(iso){if(game.capital[iso]!=null)return game.prov[game.capital[iso]];let candidates=game.prov.filter(p=>p.owner===iso);if(!candidates.length)return null;const c=candidates[candidates.length>>1];game.capital[iso]=c.id;return c}
function nameUnit(u){return u.type==='tank'?'Танковая дивизия':u.type==='art'?'Артиллерийская группа':'Пехотная дивизия'}
function resetScenario(){game.paused=true;game.date=new Date('1939-09-01T00:00:00Z');game.speed=1;game.wars=new Set(['DE|PL','DE|FR']);game.queue=[];game.units=[];game.selectedProv=null;game.selectedUnit=null;game.resources={manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100,research:40};game.tech={infantry:false,armor:false,industry:false,logistics:false,air:false};game.capital={};game.prov.forEach(p=>{p.owner=p.original;p.units=[]});
  const important={DE:['Berlin','Brandenburg','Sachsen','Lower Silesia','Bavaria'],PL:['Mazovia','Silesia','Greater Poland','Lodz'],FR:['Île-de-France','Nord','Pas-de-Calais','Alsace','Lorraine'],RU:['Moscow','Leningrad','Smolensk','Bryansk','Rostov','Kursk'],IT:['Lombardy','Lazio','Piedmont','Veneto']};
  for(const iso of Object.keys(important)){const names=important[iso];let ps=game.prov.filter(p=>p.owner===iso);for(const n of names){const found=ps.find(p=>p.name.toLowerCase().includes(n.toLowerCase()));if(found)addUnit(iso,'inf',found.id)}for(let i=0;i<Math.min(8,ps.length);i++){const p=ps[(i*7)%ps.length];if(!p.units.length)addUnit(iso,i%6===0?'tank':'inf',p.id)}}
  if(game.capital.DE==null)game.capital.DE=findCapital('DE')?.id;if(game.capital.PL==null)game.capital.PL=findCapital('PL')?.id;if(game.capital.FR==null)game.capital.FR=findCapital('FR')?.id;game.paused=false;rebuildFronts();render();log('Новая кампания: альтернативная Европа, 1 сентября 1939. Германия воюет с Польшей и Францией.');}
function rebuildFronts(){const fronts=[];for(const a of game.prov){for(const b of game.prov){if(a.id>=b.id||a.owner===b.owner||!atWar(a.owner,b.owner))continue;const d=dist(a,b);if(d<5.2)fronts.push([a,b])}}game.fronts=fronts}
function frontPath(a,b){const [x1,y1]=projection([a.cx,a.cy]),[x2,y2]=projection([b.cx,b.cy]);return `M${x1},${y1}L${x2},${y2}`}
function renderMap(){gMap.selectAll('path.province').attr('fill',d=>colorFor(d.owner)).classed('selected',d=>d.id===game.selectedProv);gFront.selectAll('*').remove();game.fronts.forEach((f,i)=>gFront.append('path').attr('class',i%3?'front':'front secondary').attr('d',frontPath(f[0],f[1])));gOrder.selectAll('*').remove();game.units.filter(u=>u.target!=null).forEach(u=>{const a=game.prov[u.prov],b=game.prov[u.target];gOrder.append('path').attr('class','order-line').attr('d',frontPath(a,b))});gUnit.selectAll('*').remove();for(const p of game.prov){if(!p.units.length)continue;const [x,y]=projection([p.cx,p.cy]);const friendly=p.units.find(u=>u.owner===game.player);gUnit.append('text').attr('class','unit-marker').attr('x',x).attr('y',y).attr('text-anchor','middle').text(`⚔${p.units.length}`).attr('fill',friendly?'#fff3a5':'#ffb0a5');}
  const labels={};game.prov.forEach(p=>{if(C[p.owner]&&!labels[p.owner])labels[p.owner]=p});gLabel.selectAll('*').remove();Object.entries(labels).forEach(([iso,p])=>{const [x,y]=projection([p.cx,p.cy]);gLabel.append('text').attr('class','country-label').attr('x',x).attr('y',y).attr('text-anchor','middle').text(C[iso][1]+' '+iso)});
}
function renderStats(){const c=C[game.player]||['—','★','#555'];$('#countryName').textContent=c[0];$('#countrySub').textContent=`${game.player} · ${game.prov.filter(p=>p.owner===game.player).length} провинций`;$('#flag').textContent=c[1];for(const [id,key] of [['manpower','manpower'],['factories','factories'],['equipment','equipment'],['oil','oil'],['steel','steel'],['pp','pp']])$('#'+id).textContent=Math.floor(game.resources[key]);$('#date').textContent=game.date.toLocaleString('ru-RU',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'});$('#speed').textContent='▶ '+game.speed+'x';$('#pause').textContent=game.paused?'▶ Продолжить':'⏸ Пауза'}
function renderArmy(){const p=game.selectedProv!=null?game.prov[game.selectedProv]:null;$('#selection').innerHTML=p?`Выбрано: <b>${esc(p.name)}</b> · ${esc(nameForIso(p.owner))}${p.owner===game.player?'':' <span class="warn">(чужая)</span>'}`:'';const us=game.units.filter(u=>u.owner===game.player);$('#units').innerHTML=us.map(u=>{const p=game.prov[u.prov];const sel=u.id===game.selectedUnit;return `<div class="unit ${sel?'sel':''}" data-u="${u.id}"><div class="top"><b>${nameUnit(u)}</b><span>${p.name}</span></div><div>Организация ${Math.round(u.org)} · Сила ${Math.round(u.strength)}</div><div class="meter"><i style="width:${u.org}%"></i></div>${u.target!=null?`<small>Приказ: ${esc(game.prov[u.target].name)} · ${Math.ceil(u.remaining)}ч</small>`:''}</div>`}).join('')||'<div class="notice">Нет дивизий.</div>';$$('.unit[data-u]').forEach(e=>e.onclick=()=>{game.selectedUnit=+e.dataset.u;game.selectedProv=game.units[game.selectedUnit].prov;render()})}
function renderProd(){const q=$('#queue');q.innerHTML=game.queue.length?game.queue.map((x,i)=>`<div class="queue-row"><b>${nameUnit({type:x.type})}</b> · ${x.days} дней</div>`).join(''):'<div class="notice">Очередь пуста.</div>'}
function renderTech(){const list=[['infantry','Пехотное оружие','+20% атака пехоты',35],['armor','Броня','открывает танки и +25% сила танков',55],['industry','Промышленность','+4 заводов',50],['logistics','Логистика','-20% потери организации',45],['air','Авиация','+25% атака при наступлении',45]];$('#techs').innerHTML=list.map(t=>`<button class="tech" data-tech="${t[0]}" ${game.tech[t[0]]?'disabled':''}><span><b>${t[1]}</b><small>${t[2]}</small></span><b>${game.tech[t[0]]?'✓':'⚙ '+t[3]}</b></button>`).join('');$$('.tech[data-tech]').forEach(b=>b.onclick=()=>research(b.dataset.tech));}
function renderDiplo(){const rows=KEYS.filter(x=>x!==game.player).map(iso=>{const war=atWar(game.player,iso);const provs=game.prov.filter(p=>p.owner===iso).length;return `<div class="country-row"><div><b>${C[iso][1]} ${C[iso][0]}</b><div class="small">${provs} провинций ${war?'· ВОЙНА':''}</div></div><button data-war="${iso}" ${war?'disabled':''}>⚔ ${war?'Война':'Объявить'}</button></div>`}).join('');$('#countries').innerHTML=rows;$$('[data-war]').forEach(b=>b.onclick=()=>declareWar(b.dataset.war));}
function render(){renderStats();renderMap();renderArmy();renderProd();renderTech();renderDiplo();}
function research(t){if(game.tech[t])return;const cost={infantry:35,armor:55,industry:50,logistics:45,air:45}[t];if(game.resources.research<cost){log('Не хватает очков исследования.');return}game.resources.research-=cost;game.tech[t]=true;if(t==='industry')game.resources.factories+=4;log('Исследовано: '+t);render()}
function declareWar(iso){if(iso===game.player||atWar(game.player,iso))return;game.wars.add(pair(game.player,iso));rebuildFronts();log(`Объявлена война: ${C[iso]?.[0]||iso}`);render()}
function startProduction(type){const cost={inf:45,art:70,tank:95}[type];const needMan={inf:25,art:30,tank:40}[type];if(game.resources.equipment<cost||game.resources.manpower<needMan){log('Не хватает техники или людских ресурсов.');return}if(type==='tank'&&!game.tech.armor){log('Сначала исследуй броню.');return}game.resources.equipment-=cost;game.resources.manpower-=needMan;game.queue.push({type,days:type==='inf'?8:type==='art'?11:16,owner:game.player});render()}
function buildFactory(){if(game.resources.pp<50){log('Нужно 50 политической власти.');return}game.resources.pp-=50;game.resources.factories+=1;log('Завод построен.');render()}
function dailyEconomy(){game.resources.steel+=game.resources.factories*.32;game.resources.oil+=Math.max(0,game.resources.factories*.16);game.resources.equipment+=game.resources.factories*(game.tech.industry?1.12:.88);game.resources.pp+=.55;game.resources.research+=.5;game.resources.manpower+=.7;for(const q of game.queue){q.days-=1}const ready=game.queue.filter(q=>q.days<=0);game.queue=game.queue.filter(q=>q.days>0);for(const q of ready){const p=findCapital(game.player);if(p)addUnit(game.player,q.type,p.id);log('Готова новая дивизия: '+nameUnit(q))}}
function enemyAI(){for(const u of game.units.filter(x=>x.owner!==game.player&&x.target==null)){const enemy=game.prov.filter(p=>p.owner===game.player&&atWar(u.owner,p.owner)&&dist(game.prov[u.prov],p)<5.4);if(enemy.length&&Math.random()<.3){const t=enemy[Math.floor(Math.random()*enemy.length)];u.target=t.id;u.remaining=clamp(6+dist(game.prov[u.prov],t)*5,6,32)}}}
function battleStep(u,hours){const target=game.prov[u.target],from=game.prov[u.prov];if(!target)return;const defender=target.units.find(x=>x.owner!==u.owner);const atk=u.attack*(game.tech.infantry&&u.type==='inf'?1.2:1)*(game.tech.air?1.25:1)*(0.55+Math.random()*.6);if(!defender){u.org-=hours*(game.tech.logistics?.45:.65);u.remaining-=hours;if(u.remaining<=0){from.units=from.units.filter(x=>x.id!==u.id);u.prov=target.id;target.owner=u.owner;target.units.push(u);u.target=null;u.remaining=0;rebuildFronts();log(`${nameUnit(u)} заняла ${target.name}`)}}else{const def=defender.attack*(0.55+Math.random()*.8);u.org-=hours*def*(game.tech.logistics?.018:.025);defender.org-=hours*atk*(game.tech.logistics?.017:.022);if(u.org<=10){u.target=null;u.remaining=0;u.org=15;log(`${nameUnit(u)} отступает от ${target.name}`)}if(defender.org<=5){const oldOwner=target.owner;target.units=target.units.filter(x=>x.id!==defender.id);from.units=from.units.filter(x=>x.id!==u.id);u.prov=target.id;target.owner=u.owner;target.units.push(u);u.target=null;u.remaining=0;u.org=Math.max(25,u.org);rebuildFronts();log(`${nameUnit(u)} прорвала фронт и захватила ${target.name} у ${nameForIso(oldOwner)}`)}}}
function hourTick(){if(game.paused)return;const hours=game.speed;game.date=new Date(game.date.getTime()+hours*3600000);for(const u of game.units){if(u.target!=null)battleStep(u,hours);else u.org=clamp(u.org+hours*.08,0,100)}if(game.date.getUTCHours()===0)dailyEconomy();if(Math.random()<.18)enemyAI();if(game.date.getTime()%86400000<3600000)rebuildFronts();const enemyProvs=game.prov.filter(p=>p.owner!==game.player&&C[p.owner]);if(!enemyProvs.length){game.paused=true;log('ПОБЕДА: все крупные государства Европы капитулировали перед вашей армией.')}renderStats();renderMap();renderArmy();}
function save(){const data={player:game.player,date:game.date.toISOString(),speed:game.speed,paused:game.paused,wars:[...game.wars],resources:game.resources,tech:game.tech,owners:game.prov.map(p=>p.owner),units:game.units.map(u=>({...u}))};localStorage.setItem('iron-front-save',JSON.stringify(data));log('Игра сохранена.');}
function load(){const raw=localStorage.getItem('iron-front-save');if(!raw){log('Сохранение не найдено.');return}try{const d=JSON.parse(raw);game.player=d.player;game.date=new Date(d.date);game.speed=d.speed;game.paused=d.paused;game.wars=new Set(d.wars);game.resources=d.resources;game.tech=d.tech;game.prov.forEach((p,i)=>{p.owner=d.owners[i]||p.original;p.units=[]});game.units=d.units.map(u=>({...u}));game.units.forEach(u=>game.prov[u.prov]?.units.push(u));rebuildFronts();$('#country').value=game.player;render();log('Сохранение загружено.')}catch(e){log('Сохранение повреждено.')}}
function bind(){KEYS.forEach(iso=>{$('#country').insertAdjacentHTML('beforeend',`<option value="${iso}">${C[iso][1]} ${C[iso][0]}</option>`)});$('#country').value=game.player;$('#country').onchange=()=>{game.player=$('#country').value;resetScenario()};$$('[data-speed]').forEach(b=>b.onclick=()=>{game.speed=+b.dataset.speed;$$('[data-speed]').forEach(x=>x.classList.toggle('active',x===b));renderStats()});$('#pause').onclick=()=>{game.paused=!game.paused;renderStats()};$('#newGame').onclick=()=>resetScenario();$('#save').onclick=save;$('#load').onclick=load;$('#recruitInf').onclick=()=>startProduction('inf');$('#recruitArt').onclick=()=>startProduction('art');$('#recruitTank').onclick=()=>startProduction('tank');$('#buildFactory').onclick=buildFactory;$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tabbody').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$('#'+b.dataset.tab).classList.remove('hidden')});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();game.paused=!game.paused;renderStats()}if(['1','2','3'].includes(e.key)){game.speed=+e.key;$$('[data-speed]').forEach(x=>x.classList.toggle('active',+x.dataset.speed===game.speed));renderStats()}});}
async function boot(){try{$('#mapStatus').textContent='Загружаем Natural Earth Admin-1…';const geo=await loadJson();game.features=geo.features.filter(f=>{const b=f.bbox;if(!b)return false;const [x1,y1,x2,y2]=b;return x2>-25&&x1<70&&y2>34&&y1<72});game.prov=game.features.map(baseProvince).filter(p=>C[p.owner]);game.features=game.prov.map(p=>p.feature);if(!game.prov.length)throw new Error('Нет европейских провинций');game.originalOwners=game.prov.map(p=>p.owner);setupMap();bind();resetScenario();$('#mapStatus').textContent=`Европа: ${game.prov.length} реальных административных провинций`;}catch(e){console.error(e);$('#mapStatus').textContent='Не удалось загрузить карту. Открой страницу с доступом к интернету.';log('Ошибка карты: '+e.message)}}
addEventListener('resize',()=>{if(!projection)return;setupMap();renderMap()});
setInterval(hourTick,900);
boot();
