const C={DE:['Германия','🇩🇪','#647b4a'],PL:['Польша','🇵🇱','#b56b67'],FR:['Франция','🇫🇷','#5476a8'],IT:['Италия','🇮🇹','#6b8b68'],GB:['Великобритания','🇬🇧','#6a667e'],RU:['Россия','🇷🇺','#7b5d57'],UA:['Украина','🇺🇦','#9a8150'],BY:['Беларусь','🇧🇾','#7b8760'],CZ:['Чехия','🇨🇿','#7c7795'],SK:['Словакия','🇸🇰','#89705a'],AT:['Австрия','🇦🇹','#8a6c69'],HU:['Венгрия','🇭🇺','#8c7b52'],RO:['Румыния','🇷🇴','#6d8875'],BG:['Болгария','🇧🇬','#7e6f8f'],GR:['Греция','🇬🇷','#617b8e'],TR:['Турция','🇹🇷','#8a6c55'],ES:['Испания','🇪🇸','#8d7651'],PT:['Португалия','🇵🇹','#6d8070'],NL:['Нидерланды','🇳🇱','#8b7055'],BE:['Бельгия','🇧🇪','#6e7088'],CH:['Швейцария','🇨🇭','#7b7b7b'],DK:['Дания','🇩🇰','#8b6460'],NO:['Норвегия','🇳🇴','#667d87'],SE:['Швеция','🇸🇪','#607d71'],FI:['Финляндия','🇫🇮','#6c7685'],EE:['Эстония','🇪🇪','#6f7d6b'],LV:['Латвия','🇱🇻','#856c66'],LT:['Литва','🇱🇹','#6f8161'],MD:['Молдова','🇲🇩','#81795a'],RS:['Сербия','🇷🇸','#8a6565'],HR:['Хорватия','🇭🇷','#6d7f67'],SI:['Словения','🇸🇮','#71818c'],BA:['Босния и Герцеговина','🇧🇦','#7e7464'],ME:['Черногория','🇲🇪','#736b7c'],AL:['Албания','🇦🇱','#78656f'],MK:['Северная Македония','🇲🇰','#8b7555'],IE:['Ирландия','🇮🇪','#5f8065'],IS:['Исландия','🇮🇸','#607a89'],XK:['Косово','🇽🇰','#80706e']};
const EUROPE=Object.keys(C),$=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)],NS='http://www.w3.org/2000/svg';
const svg=$('world');
const state={player:'DE',speed:1,paused:false,date:new Date('1939-09-01T00:00:00Z'),prov:[],units:[],selectedProv:null,selectedUnit:null,wars:new Set(['DE|PL','DE|FR']),fronts:[],resources:{manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100},tech:{infantry:false,armor:false,industry:false,logistics:false,air:false}};
const VIEW={minLon:-15,maxLon:55,minLat:32,maxLat:72,W:1200,H:700};
let timer=null,zoom=1,panX=0,panY=0;

const safe=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pair=(a,b)=>a<b?`${a}|${b}`:`${b}|${a}`;
const atWar=(a,b)=>a&&b&&a!==b&&state.wars.has(pair(a,b));
const nameIso=iso=>C[iso]?.[0]||iso||'Неизвестно';
function log(t){const e=document.createElement('div');e.textContent=t;$('#log').prepend(e);setTimeout(()=>e.remove(),6000)}
function lonLatToXY(lon,lat){const x=(lon-VIEW.minLon)/(VIEW.maxLon-VIEW.minLon)*VIEW.W*zoom+panX;const y=(VIEW.maxLat-lat)/(VIEW.maxLat-VIEW.minLat)*VIEW.H*zoom+panY;return [x,y]}
function region(iso,name,minLon,maxLon,minLat,maxLat){return {iso,name,minLon,maxLon,minLat,maxLat,units:[]}}
function makeRegions(){
  const r=[];const add=(iso,name,a,b,c,d)=>r.push(region(iso,name,a,b,c,d));
  add('IS','Исландия',-24,-14,63,67);add('IE','Ирландия',-10,-6,51,55);add('GB','Шотландия',-7,0,55,59);add('GB','Англия',-6,2,50,55);
  add('PT','Португалия',-9.5,-6.2,37,42);add('ES','Север Испании',-9.5,3.3,42,44.5);add('ES','Юг Испании',-8.8,3.2,36,42);
  add('FR','Север Франции',-5,8,47,51);add('FR','Юг Франции',-2.5,8,42,47);add('BE','Бельгия',2.5,6.5,49.4,51.6);add('NL','Нидерланды',3.2,7.3,50.7,53.6);
  add('DE','Север Германии',5.8,15.2,51.5,55.1);add('DE','Юг Германии',5.8,15.2,47.2,51.5);add('DK','Дания',8,12.7,54.5,57.8);
  add('NO','Норвегия',4,31,58,71);add('SE','Швеция',11,24.5,55,69);add('FI','Финляндия',20,32,59.5,70);add('EE','Эстония',21.5,28.2,57.4,59.8);add('LV','Латвия',20.7,28.3,55.6,58.1);add('LT','Литва',21,26.8,53.8,56.5);
  add('PL','Запад Польши',14,19.3,49,54.9);add('PL','Восток Польши',19.3,24.2,49,54.9);add('CZ','Чехия',12,19,48.5,51.2);add('SK','Словакия',16.8,22.6,47.7,49.7);add('AT','Австрия',9.5,17.2,46.3,49.1);add('CH','Швейцария',5.9,10.5,45.8,47.9);
  add('IT','Север Италии',7,14,44,47);add('IT','Юг Италии',8.5,18.7,36.5,44);add('HR','Хорватия',13.4,19.5,42.3,46.6);add('SI','Словения',13.3,16.7,45.4,46.9);add('BA','Босния и Герцеговина',15.7,19.7,42.5,45.4);add('RS','Сербия',18.8,23,42.2,46.3);add('ME','Черногория',18.4,20.4,41.8,43.6);add('AL','Албания',19,21.1,39.6,42.7);add('MK','Северная Македония',20.4,23,40.7,42.4);add('GR','Греция',19.4,28.3,34.8,41.8);add('BG','Болгария',22.3,28.7,41.1,44.3);
  add('HU','Венгрия',16,23,45.7,48.6);add('RO','Румыния',20,29.7,43.6,48.3);add('MD','Молдова',26.5,30.2,45.4,48.6);add('UA','Запад Украины',22,31,44.3,49.8);add('UA','Восток Украины',31,40.2,44.3,52.4);add('BY','Беларусь',23,32.8,51.2,56.2);add('RU','Запад России',27,42,50,63);add('RU','Северо-Запад России',27,40,63,71);add('RU','Юг России',38,55,41.5,52);add('TR','Турция',26,45,35.7,42.2);
  return r.map((p,i)=>({...p,id:i,cx:(p.minLon+p.maxLon)/2,cy:(p.minLat+p.maxLat)/2,original:p.iso}));
}
function geoBounds(p){return [p.minLon,p.minLat,p.maxLon,p.maxLat]}
function adjacent(a,b){const A=geoBounds(a),B=geoBounds(b);const gx=Math.max(0,A[0]-B[2],B[0]-A[2]);const gy=Math.max(0,A[1]-B[3],B[1]-A[3]);return Math.hypot(gx,gy)<1.35}
function rebuildFronts(){state.fronts=[];for(let i=0;i<state.prov.length;i++)for(let j=i+1;j<state.prov.length;j++){const a=state.prov[i],b=state.prov[j];if(a.iso!==b.iso&&atWar(a.iso,b.iso)&&adjacent(a,b))state.fronts.push([a,b])}}
function pathFor(p){const n=0.35;const pts=[[p.minLon+n,p.minLat],[p.maxLon-n,p.minLat],[p.maxLon,p.minLat+n],[p.maxLon,p.maxLat-n],[p.maxLon-n,p.maxLat],[p.minLon+n,p.maxLat],[p.minLon,p.maxLat-n],[p.minLon,p.minLat+n]];return pts.map((q,i)=>{const [x,y]=lonLatToXY(q[0],q[1]);return `${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join('')+'Z'}
function drawBase(){svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${VIEW.W} ${VIEW.H}`);svg.setAttribute('preserveAspectRatio','xMidYMid meet');svg.setAttribute('role','img');const sea=document.createElementNS(NS,'rect');sea.setAttribute('x',0);sea.setAttribute('y',0);sea.setAttribute('width',VIEW.W);sea.setAttribute('height',VIEW.H);sea.setAttribute('fill','#3f5a68');svg.appendChild(sea);}
function drawMap(){drawBase();state.prov.forEach(p=>{const d=document.createElementNS(NS,'path');d.classList.add('province');d.dataset.id=p.id;d.setAttribute('d',pathFor(p));d.setAttribute('fill',C[p.iso]?.[2]||'#666');d.addEventListener('click',()=>selectProv(p.id));d.addEventListener('contextmenu',e=>{e.preventDefault();issueOrder(p.id)});d.addEventListener('mousemove',e=>tooltip(e,p.id));d.addEventListener('mouseleave',hideTip);svg.appendChild(d)});renderOverlay()}
function renderOverlay(){svg.querySelectorAll('.overlay,.country-label').forEach(e=>e.remove());state.prov.forEach(p=>{const el=svg.querySelector(`path.province[data-id="${p.id}"]`);if(el){el.classList.toggle('selected',p.id===state.selectedProv);el.setAttribute('fill',C[p.iso]?.[2]||'#666')}});
  const g=document.createElementNS(NS,'g');g.classList.add('overlay');state.fronts.forEach((f,i)=>{const l=document.createElementNS(NS,'path');l.classList.add('front',i%2?'secondary':'');const a=lonLatToXY(f[0].cx,f[0].cy),b=lonLatToXY(f[1].cx,f[1].cy);l.setAttribute('d',`M${a[0]},${a[1]} L${b[0]},${b[1]}`);g.appendChild(l)});
  state.units.forEach(u=>{const p=state.prov[u.prov];if(!p)return;const [x,y]=lonLatToXY(p.cx,p.cy);const t=document.createElementNS(NS,'text');t.classList.add('unit-marker');t.setAttribute('x',x);t.setAttribute('y',y);t.setAttribute('text-anchor','middle');t.setAttribute('fill',u.owner===state.player?'#fff3a5':'#ffb0a5');t.textContent=`⚔${p.units.length}`;g.appendChild(t)});svg.appendChild(g);
  EUROPE.forEach(iso=>{const ps=state.prov.filter(p=>p.iso===iso);if(!ps.length)return;const cx=ps.reduce((s,p)=>s+p.cx,0)/ps.length,cy=ps.reduce((s,p)=>s+p.cy,0)/ps.length;const [x,y]=lonLatToXY(cx,cy);const label=document.createElementNS(NS,'text');label.classList.add('country-label');label.setAttribute('x',x);label.setAttribute('y',y);label.setAttribute('text-anchor','middle');label.textContent=C[iso][0];svg.appendChild(label)})}
function tooltip(e,id){const p=state.prov[id],tip=$('tooltip');if(!p)return;tip.style.display='block';tip.innerHTML=`<b>${safe(p.name)}</b><br>${safe(nameIso(p.iso))}<br>Дивизий: ${p.units.length}${p.iso!==state.player&&atWar(state.player,p.iso)?'<br><span class="warn">⚔ Участок фронта</span>':''}`;const r=$('map').getBoundingClientRect();tip.style.left=(e.clientX-r.left+12)+'px';tip.style.top=(e.clientY-r.top+12)+'px'}
function hideTip(){$('tooltip').style.display='none'}
function selectProv(id){state.selectedProv=id;const p=state.prov[id];const own=p.units.find(u=>u.owner===state.player);state.selectedUnit=own?own.id:null;render()}
function addUnit(owner,type,prov){const u={id:state.units.length,owner,type,prov,target:null,remaining:0,org:100,strength:type==='tank'?125:type==='art'?105:100};state.units.push(u);state.prov[prov].units.push(u);return u}
function typeName(t){return t==='tank'?'Танковая дивизия':t==='art'?'Артиллерийская группа':'Пехотная дивизия'}
function startScenario(){state.date=new Date('1939-09-01T00:00:00Z');state.units=[];state.selectedProv=null;state.selectedUnit=null;state.resources={manpower:420,factories:18,equipment:160,oil:80,steel:90,pp:100};state.tech={infantry:false,armor:false,industry:false,logistics:false,air:false};state.prov.forEach(p=>{p.owner=p.original;p.iso=p.original;p.units=[]});const setup={DE:3,PL:3,FR:3,IT:2,GB:1,RU:4,UA:2};Object.entries(setup).forEach(([iso,count])=>{state.prov.filter(p=>p.iso===iso).slice(0,count).forEach(p=>addUnit(iso,'inf',p.id))});rebuildFronts();state.paused=false;render();log('Кампания началась: 1 сентября 1939. Карта работает полностью офлайн.')}
function removeUnit(id){const u=state.units.find(x=>x.id===id);if(!u)return;state.prov[u.prov].units=state.prov[u.prov].units.filter(x=>x.id!==id);state.units=state.units.filter(x=>x.id!==id);state.units.forEach((x,i)=>x.id=i);state.selectedUnit=null}
function moveUnit(u,to){state.prov[u.prov].units=state.prov[u.prov].units.filter(x=>x.id!==u.id);u.prov=to;state.prov[to].units.push(u);u.target=null;u.remaining=0;u.org=Math.min(100,u.org+8);if(state.prov[to].owner!==u.owner)state.prov[to].owner=u.owner;state.prov[to].iso=u.owner;rebuildFronts()}
function fight(target,u){const defenders=target.units.filter(x=>x.owner!==u.owner);const atk=u.strength*(state.tech.infantry&&u.type==='inf'?1.2:1);const def=defenders.reduce((s,x)=>s+x.strength,0);if(!defenders.length){moveUnit(u,target.id);return}if(atk>def*.9){defenders.slice().forEach(d=>{d.org-=Math.max(7,atk/Math.max(1,def));if(d.org<=0)removeUnit(d.id)});u.org-=4;moveUnit(u,target.id);log(`${typeName(u.type)} заняла ${target.name}.`)}else{u.org-=6;defenders.forEach(d=>d.org-=2);if(u.org<25){u.target=null;log(`${typeName(u.type)} потеряла организацию и отступает.`)}}}
function issueOrder(targetId){if(state.selectedUnit==null){log('Сначала выбери свою дивизию.');return}const u=state.units[state.selectedUnit],b=state.prov[targetId];if(!u||u.owner!==state.player||!b)return;const a=state.prov[u.prov];if(a.id===b.id)return;if(!adjacent(a,b)){log('Можно отдавать приказ только в соседний регион.');return}if(b.owner!==u.owner&&!atWar(u.owner,b.owner)){log('Сначала объяви войну этой стране.');return}u.target=b.id;u.remaining=5;log(`${typeName(u.type)} → ${b.name}`);render()}
function tick(){if(state.paused)return;state.date=new Date(state.date.getTime()+state.speed*60*60*1000);state.resources.pp+=state.resources.factories*.08*state.speed;state.resources.oil=Math.max(0,state.resources.oil-.3*state.speed);state.resources.steel+=state.resources.factories*.04*state.speed;state.units.slice().forEach(u=>{if(u.org<100)u.org=Math.min(100,u.org+.8*state.speed);if(u.target!=null){u.remaining-=state.speed;if(u.remaining<=0){const b=state.prov[u.target];b.owner===u.owner?moveUnit(u,b.id):fight(b,u)}}});rebuildFronts();render()}
function render(){renderStats();renderArmy();renderProd();renderTech();renderCountries();renderOverlay()}
function renderStats(){const c=C[state.player];$('countryName').textContent=c[0];$('countrySub').textContent=`${state.player} · ${state.prov.filter(p=>p.owner===state.player).length} регионов`;$('flag').textContent=c[1];['manpower','factories','equipment','oil','steel','pp'].forEach(k=>$(k).textContent=Math.floor(state.resources[k]));$('date').textContent=state.date.toLocaleString('ru-RU',{timeZone:'UTC',day:'numeric',month:'long',year:'numeric',hour:'2-digit',minute:'2-digit'});$('speed').textContent='▶ '+state.speed+'x';$('pause').textContent=state.paused?'▶ Продолжить':'⏸ Пауза'}
function renderArmy(){const p=state.selectedProv!=null?state.prov[state.selectedProv]:null;$('selection').innerHTML=p?`Выбрано: <b>${safe(p.name)}</b> · ${safe(nameIso(p.owner))}`:'';const us=state.units.filter(u=>u.owner===state.player);$('units').innerHTML=us.map(u=>{const p=state.prov[u.prov];return `<div class="unit ${u.id===state.selectedUnit?'sel':''}" data-u="${u.id}"><div class="top"><b>${typeName(u.type)}</b><span>${safe(p.name)}</span></div><div>Организация ${Math.round(u.org)} · Сила ${Math.round(u.strength)}</div><div class="meter"><i style="width:${u.org}%"></i></div>${u.target!=null?`<small>Приказ: ${safe(state.prov[u.target].name)} · ${Math.ceil(u.remaining)}ч</small>`:''}</div>`}).join('')||'<div class="notice">Дивизий нет.</div>';$$('.unit[data-u]').forEach(el=>el.onclick=()=>{state.selectedUnit=+el.dataset.u;state.selectedProv=state.units[state.selectedUnit].prov;render()})}
function renderProd(){$('queue').innerHTML=`<div class="queue-row">Боеприпасы: +${Math.floor(state.resources.factories*.7)} ед./час</div><div class="queue-row">Техника: +${Math.floor(state.resources.factories*.35)} ед./час</div>`}
function renderTech(){const techs=[['infantry','Пехотное оружие','+20% атака пехоты',40],['armor','Броня','усиление танков',55],['industry','Промышленность','+4 фабрики',45],['logistics','Логистика','меньше потери организации',50],['air','Авиация','поддержка атаки',60]];$('techs').innerHTML=techs.map(([id,n,d,c])=>`<div class="tech"><div><b>${n}</b><small>${d} · ${c}🏛️</small></div><button data-tech="${id}" ${state.tech[id]||state.resources.pp<c?'disabled':''}>${state.tech[id]?'Изучено':'Изучить'}</button></div>`).join('');$$('[data-tech]').forEach(b=>b.onclick=()=>{const id=b.dataset.tech,c={infantry:40,armor:55,industry:45,logistics:50,air:60}[id];if(state.tech[id]||state.resources.pp<c)return;state.resources.pp-=c;state.tech[id]=true;if(id==='industry')state.resources.factories+=4;render()})}
function renderCountries(){const ids=EUROPE.filter(i=>state.prov.some(p=>p.owner===i));$('countries').innerHTML=ids.map(i=>{const n=state.prov.filter(p=>p.owner===i).length,war=atWar(state.player,i);return `<div class="country-row"><div><b>${C[i][1]} ${C[i][0]}</b><div class="small">${n} регионов · ${war?'война':'мир'}</div></div>${i===state.player?'':`<button data-war="${i}" ${war?'disabled':''}>${war?'Война':'Объявить войну'}</button>`}</div>`}).join('');$$('[data-war]').forEach(b=>b.onclick=()=>{const iso=b.dataset.war;state.wars.add(pair(state.player,iso));rebuildFronts();log(`Объявлена война: ${nameIso(iso)}.`);render()})}
function saveGame(){localStorage.setItem('iron-front-save-v2',JSON.stringify({player:state.player,speed:state.speed,paused:state.paused,date:state.date.toISOString(),wars:[...state.wars],prov:state.prov.map(p=>({owner:p.owner})),units:state.units.map(u=>({...u})),resources:state.resources,tech:state.tech}));log('Игра сохранена локально.')}
function loadGame(){try{const s=JSON.parse(localStorage.getItem('iron-front-save-v2')||'null');if(!s){log('Сохранения нет.');return}state.player=s.player;state.speed=s.speed;state.paused=s.paused;state.date=new Date(s.date);state.wars=new Set(s.wars);state.resources=s.resources;state.tech=s.tech;state.prov.forEach((p,i)=>{p.owner=s.prov[i]?.owner||p.original;p.iso=p.owner;p.units=[]});state.units=s.units.map(u=>({...u}));state.units.forEach(u=>state.prov[u.prov]?.units.push(u));rebuildFronts();$('country').value=state.player;render();log('Сохранение загружено.')}catch(e){log('Сохранение повреждено. Начни новую игру.')}}
function fillCountrySelect(){const sel=$('country');sel.innerHTML=EUROPE.map(i=>`<option value="${i}">${C[i][1]} ${C[i][0]}</option>`).join('');sel.value=state.player;sel.onchange=()=>{state.player=sel.value;startScenario()}}
function wire(){fillCountrySelect();$$('.speeds button').forEach(b=>b.onclick=()=>{state.speed=+b.dataset.speed;render()});$('pause').onclick=()=>{state.paused=!state.paused;render()};$('newGame').onclick=startScenario;$('save').onclick=saveGame;$('load').onclick=loadGame;$('buildFactory').onclick=()=>{if(state.resources.pp<50){log('Не хватает политической власти.');return}state.resources.pp-=50;state.resources.factories++;render()};[['recruitInf','inf',30],['recruitArt','art',45],['recruitTank','tank',70]].forEach(([id,type,cost])=>$(id).onclick=()=>{if(state.resources.manpower<20||state.resources.equipment<cost){log('Не хватает людских ресурсов или техники.');return}const p=state.prov.find(p=>p.owner===state.player);if(!p){log('Нет контролируемого региона.');return}state.resources.manpower-=20;state.resources.equipment-=cost;addUnit(state.player,type,p.id);render()});$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tabbody').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});window.addEventListener('resize',drawMap);window.addEventListener('keydown',e=>{if(e.code==='Space'){state.paused=!state.paused;render()}if(['1','2','3'].includes(e.key)){state.speed=+e.key;render()}});let dragging=false,last=[0,0];svg.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(1,Math.min(2.7,zoom*(e.deltaY<0?1.12:.9)));drawMap()},{passive:false});svg.addEventListener('mousedown',e=>{if(e.button===0){dragging=true;last=[e.clientX,e.clientY]}});window.addEventListener('mouseup',()=>dragging=false);window.addEventListener('mousemove',e=>{if(dragging){panX+=(e.clientX-last[0])*.8;panY+=(e.clientY-last[1])*.8;last=[e.clientX,e.clientY];drawMap()}})}
state.prov=makeRegions();
wire();startScenario();timer=setInterval(tick,1000);
